version: 0.2

phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm install
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm run build
      - npm run test
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR; tar -zcvf asu-unity.tar.gz dist
artifacts:
  files:
    - dist/*
    - asu-unity.tar.gz
  discard-paths: yes