name: development-workflow
on:
  push:
    branches: ["develop-gha"]

jobs:
  run-yarn-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GH_TOKEN: ${{ secrets.ASU_DEV_STACK_GHP }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        node: ["12", "14"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node and create .npmrc
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://npm.pkg.github.com"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install and build
        run: |
          yarn install
          yarn build

      - name: Run tests
        run: |
          echo 'Tests temporarily disabled'

      - name: Yarn publish packages
        run: |
          yarn publish-packages

      - name: Publish to Github Pages
        run: |
          yarn deploy-storybook
