name: development-workflow
on:
  push:
    branches: ["develop-gha"]

jobs:
  run-yarn-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14"]
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      # This step must be ran here as well because some packages have other asu packages as dependencies
      # - name: Setup NPM registry
      #   run: |
      #    echo "registry=https://registry.web.asu.edu/" > ~/.npmrc
      #    echo "always-auth=true" >> ~/.npmrc
      #    echo "//registry.web.asu.edu/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # yarn build between install and deploy
      - name: yarn install, build and build-storybook
        run: |
          yarn install

          yarn deploy-storybook
        # Dry run build storybook here, so that each package has a built storybook to test in next step. Would remove
        # Redundancy of building each storybook separately, then having to rebuild monorepo storybook

  # run-yarn-test:
  #   runs-on: ubuntu-latest
  #   needs: run-yarn-build
  #   steps:
  #     - run: |
  #       echo 'Tests temporarily disabled'

  # build-and-push-image:
  #   runs-on: ubuntu-latest
  #   needs: run-yarn-test
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  # deploy-storybook:
  #   runs-on: ubuntu-latest
  #   needs: run-yarn-test
  #   steps:
  #     - run: |
  #       yarn deploy-storybook
